/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#633c15",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#2e1600",
        "tertiary-fixed-dim": "#f5bb89",
        "secondary-fixed-dim": "#cfc6ae",
        "on-secondary-fixed-variant": "#4c4634",
        "on-primary-fixed-variant": "#5a4400",
        "on-primary-fixed": "#251a00",
        "secondary": "#cfc6ae",
        "error-container": "#93000a",
        "tertiary-container": "#dfa877",
        "surface-tint": "#e7c268",
        "on-surface": "#e5e2e1",
        "on-secondary-fixed": "#201b0c",
        "tertiary": "#fdc390",
        "surface-container-low": "#1c1b1b",
        "primary-container": "#d2af57",
        "on-secondary-container": "#c1b8a1",
        "error": "#ffb4ab",
        "surface-variant": "#353534",
        "tertiary-fixed": "#ffdcc1",
        "surface": "#131313",
        "on-surface-variant": "#d0c5af",
        "primary-fixed": "#ffdf96",
        "on-tertiary": "#4a2803",
        "surface-container-highest": "#353534",
        "secondary-fixed": "#ece2c9",
        "primary-fixed-dim": "#e7c268",
        "inverse-primary": "#765a05",
        "surface-bright": "#3a3939",
        "on-tertiary-fixed-variant": "#653e17",
        "on-primary": "#3e2e00",
        "on-secondary": "#35301f",
        "on-error": "#690005",
        "outline-variant": "#4d4635",
        "outline": "#99907c",
        "on-primary-container": "#574200",
        "surface-dim": "#131313",
        "inverse-surface": "#e5e2e1",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-high": "#2a2a2a",
        "background": "#131313",
        "secondary-container": "#4f4936",
        "on-background": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "primary": "#f0ca6f",
        "surface-container": "#201f1f"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Work Sans", "sans-serif"],
        "label": ["Work Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
